provider: ollama
model_name: qwen2.5:3b
options:
  seed: null
  temperature: 0.5
  context_window: 8192
  max_output_tokens: 1024
  top_k: null
  top_p: 0.9
  min_p: null
config:
  stream: false
  think: false
  keep_alive: 60m
